name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl

      - name: Install Dependencies
        run: composer install

      - name: Create WP Tests Config
        run: |
          cat <<EOF > wp-tests-config.php
          <?php
          define( 'ABSPATH', '$(pwd)/vendor/wp-phpunit/wp-phpunit/src/' );
          define( 'WP_TESTS_DOMAIN', 'localhost' );
          define( 'WP_TESTS_EMAIL', 'admin@example.org' );
          define( 'WP_TESTS_TITLE', 'Test Site' );
          define( 'WP_PHP_BINARY', 'php' );
          define( 'DB_NAME', 'wordpress_test' );
          define( 'DB_USER', 'root' );
          define( 'DB_PASS', 'root' );
          define( 'DB_HOST', 'localhost' );
          \$table_prefix = 'wptests_';
          EOF

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit --configuration phpunit.xml.dist
