name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl
          tools: phpunit

      - name: Install Dependencies
        run: composer install

      - name: Setup Database
        run: |
          mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE wordpress_test;"

      - name: Install WP Tests Setup
        run: |
          bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 latest

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit --configuration phpunit.xml.dist

